### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by binnes** [openshift-cs/okd.io#231]
@sandrobonazzola  I merged #222 and the build broke as there is a broken link in file overview.md in directory docs/wg_virt.

Link <https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-k[…]onverged-cluster-operator-main-okd-hco-e2e-image-index-gcp> returns **Error: 500 Internal Server Error**

Not sure if this is a temporary issue with prow or the link is invalid?

**Comment by sandrobonazzola** [comment]
We should enable a github action to run `build.sh` on patch submission so we'll get early notification if the patch introduces broken links. I had an issue on my local system due to linkchecker not requiring the correct version of BeautifulSoup4 so it silently passed the tests just because it didn't run.
